# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
asphalt = "jacktabscode/asphalt@0.8.1"
darklua = "seaofvoices/darklua@0.14.0"
lune = "lune-org/lune@0.8.9"
mantle = "blake-mealey/mantle@0.11.17-prerelease"
rojo = "rojo-rbx/rojo@7.4.4"
