name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'src/**/*'
      - assets
      - build.project.json
      - mantle.yaml
      - package.json
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install roblox-ts
        run: pnpm add roblox-ts

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@d49be92bd9502180218c3f43e7988faa945217b0 # v0.1.2

      - name: Compile
        run: pnpm prod:build --verbose

      - name: Build project
        run: rojo build ./build.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: place
          path: place.rbxlx
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@d49be92bd9502180218c3f43e7988faa945217b0 # v0.1.2

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      # As ROBLOSECURITY keys are region locked, we need to use a VPN to ensure
      # the github actions runner is in the same region as our Roblox account.
      - name: WireGuard Connection
        run: |
          sudo apt install resolvconf wireguard
          echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf
          sudo chmod 600 wg0.conf
          echo "setting config"
          sudo wg-quick up ./wg0.conf

        shell: bash

      # Ensure the IP has changed before deploying
      - name: Poll for IP Change
        run: |
          elapsed=0
          while true; do
            response=$(curl -s 'https://httpbin.org/ip')
            content=$(echo $response | jq -r '.origin')
            if [ "$content" == "104.199.120.221" ]; then
              break
            fi
            if [ $elapsed -ge 20 ]; then
              echo "Timeout reached!"
              exit 1
            fi
            echo "Polling.. Elapsed: $elapsed, IP: $content"
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Success!"

      - name: Deploy game
        run: mantle deploy mantle.yaml --allow-purchases --environment production
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}

  tag:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      - name: Create a GitHub release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: place.rbxlx
